version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile  
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      -laravel_network
    depends_on:
      - db
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: PI
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
