version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:r9hPXv/8dwd5c5ZEBUoHnh4Ci+EypnxK3XBi6lMmGxU=
      - APP_DEBUG=true
      - APP_TIMEZONE=UTC
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=PI
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: